### ISSUE TITLE
No r value at a slope of zero

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#62]
1. Put two points directly on top of each other.
2. Drag one point out horizontally, very carefully. Moving the smallest amount vertically ruins this.
3. The best-fit line will have an equation, but the correlation coefficient will be blank or zero.
4. One can continue to carefully drag horizontally as far as they want, all while r never updates.

![noratzero](https://cloud.githubusercontent.com/assets/5863899/14392341/20adf402-fd7e-11e5-9069-1c9f357effe9.PNG)

Seen on Win 10 Chrome. For phetsims/tasks/issues/570.

Troubleshooting information:
Name: ‪Least-Squares Regression‬
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.0-dev.1/least-squares-regression_en.html
Version: 1.1.0-dev.1 2016-04-07 21:17:20 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Language: en-US
Window: 2560x1315
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"084c71cf","branch":"master"},"babel":{"sha":"df43e3d8","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"b2e0b31e","branch":"master"},"dot":{"sha":"33ae235e","branch":"master"},"joist":{"sha":"ecd8d968","branch":"master"},"kite":{"sha":"24ad131a","branch":"master"},"least-squares-regression":{"sha":"b1bb392a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"d7eed2d1","branch":"master"},"scenery":{"sha":"7db0478c","branch":"master"},"scenery-phet":{"sha":"71c5dea5","branch":"master"},"sherpa":{"sha":"b74418c0","branch":"master"},"sun":{"sha":"953074cc","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"}}

**Comment by jessegreenberg** [comment]
this.graph.getPearsonCoefficientCorrelation() is returning null in this case, so the string is empty.

**Comment by jessegreenberg** [comment]
Actually, a horizontal line is _supposed_ to have an undefined pearson correlation coefficient. http://mathworld.wolfram.com/CorrelationCoefficient.html

For a horizontal line, `r = ∑((X - My)(Y - Mx)) / √((SSx)(SSy))` results in 0/0 which is undefined.  So this issue is that it is _not_ showing undefined for a horizontal line consistently.

**Comment by jessegreenberg** [comment]
Looks like the update function was returning early without updating the text which is why we would occasionally see +/- 1.00 for a horizontal line. We are still observing +/- 0.00 sometimes for a horizontal line.  This is likely due to a presision issue in Graph.getPearsonCorrelationCoefficient()

**Comment by jessegreenberg** [comment]
Indeed, when we hit this case the denominator is 1.909526758130271e-21 when it should be 0.

**Comment by jessegreenberg** [comment]
This should be fixed with the above commits.  Closing.

**Comment by elisemorgan** [comment]
@jessegreenberg I am still seeing empty r, +0, and -0 for a horizontal line. 
![screen shot 2016-04-13 at 11 27 46 am](https://cloud.githubusercontent.com/assets/12610678/14502933/061d8742-016b-11e6-9747-00e93f4d7a7d.png)
![screen shot 2016-04-13 at 11 27 30 am](https://cloud.githubusercontent.com/assets/12610678/14502935/065b293a-016b-11e6-935b-fc7dc70154f1.png)
![screen shot 2016-04-13 at 11 27 20 am](https://cloud.githubusercontent.com/assets/12610678/14502932/0619c8b4-016b-11e6-8663-67a199ac122f.png)

**Comment by elisemorgan** [comment]
Creating a new issue since I can't reopen this one https://github.com/phetsims/least-squares-regression/issues/63
