### ISSUE TITLE
data points detach from residuals

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/least-squares-regression#93]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1190, with residuals and square residuals checked, if I add data points to the play area, switch to another graph and then back to custom, the data points separate from the residual lines and squares. This doesn't occur in published. 

**Steps to reproduce**
1. Check all boxes in Best-Fit Line accordion panel: Best-Fit Line, Residuals, and Square Residuals
2. Add 3 data points to the play area in a diagonal
3. Select Height vs. Shoe Size from the combo box
4. Select Custom
5. Move a data point

**Visuals**
<img width="1111" alt="Screenshot 2024-12-18 at 4 35 42 PM" src="https://github.com/user-attachments/assets/67497f6e-0a9a-4948-93fe-849c7a01a931" />

**Comment by Nancy-Salpepi** [comment]
This also happens with My Line:
<img width="1111" alt="Screenshot 2024-12-18 at 5 02 40 PM" src="https://github.com/user-attachments/assets/74c20cf8-93cd-407f-a48a-ad2b71f23eeb" />

**Comment by samreid** [comment]
This could be causing a memory leak #96

**Comment by samreid** [comment]
The simulation is very complex and confusing about when Residual instances are created, wrapped in Properties, and sometimes DataPoints are disposed or reused, and with respect to pooling. This patch removes Residual and Residual nodes and has no memory leak.

<details>

```diff

Subject: [PATCH] Rename vars, see https://github.com/phetsims/least-squares-regression/issues/96
---
Index: js/least-squares-regression/model/Residual.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/model/Residual.ts b/js/least-squares-regression/model/Residual.ts
--- a/js/least-squares-regression/model/Residual.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/model/Residual.ts	(date 1734713692231)
@@ -31,7 +31,7 @@
    */
   public readonly isSquaredResidualToTheLeft: boolean;
 
-  public constructor(
+  private constructor(
     public readonly dataPoint: DataPoint,
     slope: number, intercept: number ) {
 
Index: js/least-squares-regression/view/GraphAxesNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/view/GraphAxesNode.ts b/js/least-squares-regression/view/GraphAxesNode.ts
--- a/js/least-squares-regression/view/GraphAxesNode.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/view/GraphAxesNode.ts	(date 1734714020819)
@@ -72,19 +72,28 @@
 
     showGridProperty.link( showGridPropertyObserver );
 
+    const xAxisNode = new XAxisNode( dataSet, modelViewTransform );
+    const yAxisNode = new YAxisNode( dataSet, modelViewTransform );
+    const xLabelNode = new XLabelNode( dataSet, modelViewTransform );
+    const yLabelNode = new YLabelNode( dataSet, modelViewTransform );
     super( {
       children: [
         new BackgroundNode( dataSet, modelViewTransform ),
         gridNode,
-        new XAxisNode( dataSet, modelViewTransform ),
-        new YAxisNode( dataSet, modelViewTransform ),
-        new XLabelNode( dataSet, modelViewTransform ),
-        new YLabelNode( dataSet, modelViewTransform )
+        xAxisNode,
+        yAxisNode,
+        xLabelNode,
+        yLabelNode
       ]
     } );
 
     this.disposeEmitter.addListener( () => {
       showGridProperty.unlink( showGridPropertyObserver );
+      xAxisNode.dispose();
+      yAxisNode.dispose();
+      xLabelNode.dispose();
+      yLabelNode.dispose();
+      gridNode.dispose();
     } );
   }
 }
@@ -302,6 +311,10 @@
       maxWidth: MAX_LABEL_WIDTH
     } );
     this.addChild( xLabelNode );
+
+    this.disposeEmitter.addListener( () => {
+      xLabelNode.dispose();
+    } );
   }
 }
 
@@ -327,6 +340,9 @@
     } );
     this.addChild( yLabelNode );
 
+    this.disposeEmitter.addListener( () => {
+      yLabelNode.dispose();
+    } );
   }
 }
 
Index: js/least-squares-regression/view/GraphNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/view/GraphNode.ts b/js/least-squares-regression/view/GraphNode.ts
--- a/js/least-squares-regression/view/GraphNode.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/view/GraphNode.ts	(date 1734713745525)
@@ -77,7 +77,7 @@
     Multilink.multilink( [ graph.angleProperty, graph.interceptProperty ], ( angle, intercept ) => {
       const slope = graph.slope( angle );
       updateMyLine( slope, intercept );
-      graph.updateMyLineResiduals();
+      // graph.updateMyLineResiduals();
     } );
 
     // we will add all the residuals in a separate node
@@ -85,53 +85,53 @@
 
     // Handle the comings and goings of 'My Line' Residuals. Recall that graph.myLineResiduals is an
     // observable array of Property.<Residual>
-    graph.myLineResiduals.addItemAddedListener( addedResidualProperty => {
-
-      // Create and add the view representation for this residual.
-      const residualNode = new ResidualLineAndSquareNode(
-        addedResidualProperty,
-        LeastSquaresRegressionConstants.MY_LINE_COLOR,
-        this.viewBounds,
-        modelViewTransform,
-        graph.myLineResidualsVisibleProperty,
-        graph.myLineSquaredResidualsVisibleProperty );
-      residualsLayer.addChild( residualNode );
-    } );
-    graph.myLineResiduals.addItemRemovedListener( removedResidualProperty => {
-
-      // find the matching ResidualLineAndSquareNode
-      const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
-      assert && assert( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
-      residualsLayer.removeChild( residualNode[ 0 ] );
-      residualNode[ 0 ].dispose();
-    } );
-
-    // Handle the comings and goings of Best Fit Line Residuals. Recall that graph.bestFitResiduals is an
-    // observable array of Property.<Residual>
-    graph.bestFitLineResiduals.addItemAddedListener( addedResidualProperty => {
-
-      // Create and add the view representation for this residual.
-      const residualNode = new ResidualLineAndSquareNode(
-        addedResidualProperty,
-        LeastSquaresRegressionConstants.BEST_FIT_LINE_COLOR,
-        this.viewBounds,
-        modelViewTransform,
-        graph.bestFitLineResidualsVisibleProperty,
-        graph.bestFitLineSquaredResidualsVisibleProperty );
-      residualsLayer.addChild( residualNode );
-
-      this.bestFitResiduals.push( residualNode );
-    } );
-    // Add the removal listener for if and when this residual is removed from the model.
-    graph.bestFitLineResiduals.addItemRemovedListener( removedResidualProperty => {
-
-      // Find the matching ResidualLineAndSquareNode
-      const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
-      affirm( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
-      arrayRemove( this.bestFitResiduals, residualNode[ 0 ] );
-      residualsLayer.removeChild( residualNode[ 0 ] );
-      residualNode[ 0 ].dispose();
-    } );
+    // graph.myLineResiduals.addItemAddedListener( addedResidualProperty => {
+    //
+    //   // Create and add the view representation for this residual.
+    //   const residualNode = new ResidualLineAndSquareNode(
+    //     addedResidualProperty,
+    //     LeastSquaresRegressionConstants.MY_LINE_COLOR,
+    //     this.viewBounds,
+    //     modelViewTransform,
+    //     graph.myLineResidualsVisibleProperty,
+    //     graph.myLineSquaredResidualsVisibleProperty );
+    //   residualsLayer.addChild( residualNode );
+    // } );
+    // graph.myLineResiduals.addItemRemovedListener( removedResidualProperty => {
+    //
+    //   // find the matching ResidualLineAndSquareNode
+    //   const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
+    //   assert && assert( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
+    //   residualsLayer.removeChild( residualNode[ 0 ] );
+    //   residualNode[ 0 ].dispose();
+    // } );
+    //
+    // // Handle the comings and goings of Best Fit Line Residuals. Recall that graph.bestFitResiduals is an
+    // // observable array of Property.<Residual>
+    // graph.bestFitLineResiduals.addItemAddedListener( addedResidualProperty => {
+    //
+    //   // Create and add the view representation for this residual.
+    //   const residualNode = new ResidualLineAndSquareNode(
+    //     addedResidualProperty,
+    //     LeastSquaresRegressionConstants.BEST_FIT_LINE_COLOR,
+    //     this.viewBounds,
+    //     modelViewTransform,
+    //     graph.bestFitLineResidualsVisibleProperty,
+    //     graph.bestFitLineSquaredResidualsVisibleProperty );
+    //   residualsLayer.addChild( residualNode );
+    //
+    //   this.bestFitResiduals.push( residualNode );
+    // } );
+    // // Add the removal listener for if and when this residual is removed from the model.
+    // graph.bestFitLineResiduals.addItemRemovedListener( removedResidualProperty => {
+    //
+    //   // Find the matching ResidualLineAndSquareNode
+    //   const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
+    //   affirm( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
+    //   arrayRemove( this.bestFitResiduals, residualNode[ 0 ] );
+    //   residualsLayer.removeChild( residualNode[ 0 ] );
+    //   residualNode[ 0 ].dispose();
+    // } );
 
     // Hide or show the visibility of 'MyLine' and 'BestFitLine', both listeners are present for the lifetime of the sim
     graph.myLineVisibleProperty.linkAttribute( this.myLine, 'visible' );
Index: js/least-squares-regression/model/Graph.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/model/Graph.ts b/js/least-squares-regression/model/Graph.ts
--- a/js/least-squares-regression/model/Graph.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/model/Graph.ts	(date 1734713745517)
@@ -10,17 +10,14 @@
  */
 
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
-import createObservableArray, { ObservableArray } from '../../../../axon/js/createObservableArray.js';
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
 import NumberProperty from '../../../../axon/js/NumberProperty.js';
-import Property from '../../../../axon/js/Property.js';
 import TReadOnlyProperty from '../../../../axon/js/TReadOnlyProperty.js';
 import Bounds2 from '../../../../dot/js/Bounds2.js';
 import Range from '../../../../dot/js/Range.js';
 import Vector2 from '../../../../dot/js/Vector2.js';
 import leastSquaresRegression from '../../leastSquaresRegression.js';
 import DataPoint from './DataPoint.js';
-import Residual from './Residual.js';
 
 /**
  * Graph model for handling data points, residuals, and statistics related to lines of best fit.
@@ -48,8 +45,8 @@
 
   // Observable arrays for residuals
   // Each entry is a Property<Residual>.
-  public readonly myLineResiduals: ObservableArray<Property<Residual>>;
-  public readonly bestFitLineResiduals: ObservableArray<Property<Residual>>;
+  // public readonly myLineResiduals: ObservableArray<Property<Residual>>;
+  // public readonly bestFitLineResiduals: ObservableArray<Property<Residual>>;
 
   // Array of dataPoints currently on the graph
   public dataPointsOnGraph: DataPoint[];
@@ -104,8 +101,8 @@
     this.bounds = new Bounds2( 0, 0, 1, 1 );
 
     // observable arrays of the line and squared residuals (wrapped in a property) for MyLine and BestFitLine
-    this.myLineResiduals = createObservableArray<Property<Residual>>();
-    this.bestFitLineResiduals = createObservableArray<Property<Residual>>();
+    // this.myLineResiduals = createObservableArray<Property<Residual>>();
+    // this.bestFitLineResiduals = createObservableArray<Property<Residual>>();
 
     // array of the dataPoints that are overlapping the graph.
     this.dataPointsOnGraph = [];
@@ -128,8 +125,8 @@
     this.bestFitLineShowResidualsProperty.reset();
     this.bestFitLineShowSquaredResidualsProperty.reset();
     this.dataPointsOnGraph = [];
-    this.myLineResiduals.clear();
-    this.bestFitLineResiduals.clear();
+    // this.myLineResiduals.clear();
+    // this.bestFitLineResiduals.clear();
   }
 
   /**
@@ -137,8 +134,8 @@
    */
   public resetOnChangeOfDataSet(): void {
     this.dataPointsOnGraph = [];
-    this.myLineResiduals.clear();
-    this.bestFitLineResiduals.clear();
+    // this.myLineResiduals.clear();
+    // this.bestFitLineResiduals.clear();
   }
 
   /**
@@ -157,8 +154,8 @@
    * Update the model Residuals for 'My Line' and 'Best Fit Line'.
    */
   private update(): void {
-    this.updateMyLineResiduals();
-    this.updateBestFitLineResiduals();
+    // this.updateMyLineResiduals();
+    // this.updateBestFitLineResiduals();
   }
 
   /**
@@ -168,70 +165,70 @@
     return Math.tan( angle ) * this.bounds.height / this.bounds.width;
   }
 
-  /**
-   * Add a 'My Line' model Residual to a dataPoint.
-   */
-  private addMyLineResidual( dataPoint: DataPoint ): void {
-    const myLineResidual = new Residual( dataPoint, this.slope( this.angleProperty.value ), this.interceptProperty.value );
-    this.myLineResiduals.push( new Property( myLineResidual ) );
-  }
-
-  /**
-   * Add a 'Best Fit Line' model Residual to a dataPoint.
-   */
-  private addBestFitLineResidual( dataPoint: DataPoint ): void {
-    const linearFitParameters = this.getLinearFit();
-    const bestFitLineResidual = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
-    this.bestFitLineResiduals.push( new Property( bestFitLineResidual ) );
-  }
-
-  /**
-   * Remove the 'My Line' model Residual attached to a dataPoint.
-   */
-  private removeMyLineResidual( dataPoint: DataPoint ): void {
-    const myLineResidualsCopy = this.myLineResiduals.slice();
-    myLineResidualsCopy.forEach( myLineResidualProperty => {
-      if ( myLineResidualProperty.value.dataPoint === dataPoint ) {
-        this.myLineResiduals.remove( myLineResidualProperty );
-      }
-    } );
-  }
-
-  /**
-   * Remove a 'Best Fit Line' model Residual attached to a dataPoint.
-   */
-  private removeBestFitLineResidual( dataPoint: DataPoint ): void {
-    const bestFitLineResidualsCopy = this.bestFitLineResiduals.slice();
-    bestFitLineResidualsCopy.forEach( bestFitLineResidualProperty => {
-      if ( bestFitLineResidualProperty.value.dataPoint === dataPoint ) {
-        this.bestFitLineResiduals.remove( bestFitLineResidualProperty );
-      }
-    } );
-  }
-
-  /**
-   * Update all 'My Line' model Residuals
-   * (Necessary to update when the slope and the intercept of 'My Line' are modified)
-   */
-  public updateMyLineResiduals(): void {
-    this.myLineResiduals.forEach( residualProperty => {
-      const dataPoint = residualProperty.value.dataPoint;
-      residualProperty.value = new Residual( dataPoint, this.slope( this.angleProperty.value ), this.interceptProperty.value );
-    } );
-  }
-
-  /**
-   * Update all 'Best Fit Line' model Residuals.
-   */
-  private updateBestFitLineResiduals(): void {
-    if ( this.isLinearFitDefined() ) {
-      const linearFitParameters = this.getLinearFit();
-      this.bestFitLineResiduals.forEach( residualProperty => {
-        const dataPoint = residualProperty.value.dataPoint;
-        residualProperty.value = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
-      } );
-    }
-  }
+  // /**
+  //  * Add a 'My Line' model Residual to a dataPoint.
+  //  */
+  // private addMyLineResidual( dataPoint: DataPoint ): void {
+  //   const myLineResidual = new Residual( dataPoint, this.slope( this.angleProperty.value ), this.interceptProperty.value );
+  //   this.myLineResiduals.push( new Property( myLineResidual ) );
+  // }
+  //
+  // /**
+  //  * Add a 'Best Fit Line' model Residual to a dataPoint.
+  //  */
+  // private addBestFitLineResidual( dataPoint: DataPoint ): void {
+  //   const linearFitParameters = this.getLinearFit();
+  //   const bestFitLineResidual = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
+  //   this.bestFitLineResiduals.push( new Property( bestFitLineResidual ) );
+  // }
+  //
+  // /**
+  //  * Remove the 'My Line' model Residual attached to a dataPoint.
+  //  */
+  // private removeMyLineResidual( dataPoint: DataPoint ): void {
+  //   const myLineResidualsCopy = this.myLineResiduals.slice();
+  //   myLineResidualsCopy.forEach( myLineResidualProperty => {
+  //     if ( myLineResidualProperty.value.dataPoint === dataPoint ) {
+  //       this.myLineResiduals.remove( myLineResidualProperty );
+  //     }
+  //   } );
+  // }
+  //
+  // /**
+  //  * Remove a 'Best Fit Line' model Residual attached to a dataPoint.
+  //  */
+  // private removeBestFitLineResidual( dataPoint: DataPoint ): void {
+  //   const bestFitLineResidualsCopy = this.bestFitLineResiduals.slice();
+  //   bestFitLineResidualsCopy.forEach( bestFitLineResidualProperty => {
+  //     if ( bestFitLineResidualProperty.value.dataPoint === dataPoint ) {
+  //       this.bestFitLineResiduals.remove( bestFitLineResidualProperty );
+  //     }
+  //   } );
+  // }
+  //
+  // /**
+  //  * Update all 'My Line' model Residuals
+  //  * (Necessary to update when the slope and the intercept of 'My Line' are modified)
+  //  */
+  // public updateMyLineResiduals(): void {
+  //   this.myLineResiduals.forEach( residualProperty => {
+  //     const dataPoint = residualProperty.value.dataPoint;
+  //     residualProperty.value = new Residual( dataPoint, this.slope( this.angleProperty.value ), this.interceptProperty.value );
+  //   } );
+  // }
+  //
+  // /**
+  //  * Update all 'Best Fit Line' model Residuals.
+  //  */
+  // private updateBestFitLineResiduals(): void {
+  //   if ( this.isLinearFitDefined() ) {
+  //     const linearFitParameters = this.getLinearFit();
+  //     this.bestFitLineResiduals.forEach( residualProperty => {
+  //       const dataPoint = residualProperty.value.dataPoint;
+  //       residualProperty.value = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
+  //     } );
+  //   }
+  // }
 
   /**
    * Add Data Points on Graph in bulk, for performance reasons.
@@ -244,24 +241,24 @@
       this.dataPointsOnGraph.push( dataPoint );
     } );
 
-    const mySlope = this.slope( this.angleProperty.value );
-    const myIntercept = this.interceptProperty.value;
+    // const mySlope = this.slope( this.angleProperty.value );
+    // const myIntercept = this.interceptProperty.value;
 
     // add a 'myLineResidual' for every single dataPoint
-    dataPoints.forEach( dataPoint => {
-      const myLineResidual = new Residual( dataPoint, mySlope, myIntercept );
-      this.myLineResiduals.push( new Property( myLineResidual ) );
-    } );
-
-    // add a 'best fit Line' residual  for every single dataPoint
-    // unless there is not  linearFit (because there is less than 2 data points on the board for instance)
-    if ( this.isLinearFitDefined() ) {
-      const linearFitParameters = this.getLinearFit();
-      dataPoints.forEach( dataPoint => {
-        const bestFitLineResidual = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
-        this.bestFitLineResiduals.push( new Property( bestFitLineResidual ) );
-      } );
-    }
+    // dataPoints.forEach( dataPoint => {
+    //   const myLineResidual = new Residual( dataPoint, mySlope, myIntercept );
+    //   this.myLineResiduals.push( new Property( myLineResidual ) );
+    // } );
+    //
+    // // add a 'best fit Line' residual  for every single dataPoint
+    // // unless there is not  linearFit (because there is less than 2 data points on the board for instance)
+    // if ( this.isLinearFitDefined() ) {
+    //   const linearFitParameters = this.getLinearFit();
+    //   dataPoints.forEach( dataPoint => {
+    //     const bestFitLineResidual = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
+    //     this.bestFitLineResiduals.push( new Property( bestFitLineResidual ) );
+    //   } );
+    // }
   }
 
   /**
@@ -284,21 +281,21 @@
    */
   public addPointAndResiduals( dataPoint: DataPoint ): void {
     this.dataPointsOnGraph.push( dataPoint );
-    this.addMyLineResidual( dataPoint );
+    // this.addMyLineResidual( dataPoint );
 
     // a BestFit line exists if there are two dataPoints or more.
     // if there are two dataPoints on the graph, we don't add my bestFitLine residual
     // since the residual are zero by definition
     // if there are exactly three data points on the graph we need to add three residuals
-    if ( this.dataPointsOnGraph.length === 3 ) {
-      this.dataPointsOnGraph.forEach( dataPoint => {
-        this.addBestFitLineResidual( dataPoint );
-      } );
-    }
-    // for three dataPoints or more there is one residual for every dataPoint added
-    if ( this.dataPointsOnGraph.length > 3 ) {
-      this.addBestFitLineResidual( dataPoint );
-    }
+    // if ( this.dataPointsOnGraph.length === 3 ) {
+    //   this.dataPointsOnGraph.forEach( dataPoint => {
+    //     this.addBestFitLineResidual( dataPoint );
+    //   } );
+    // }
+    // // for three dataPoints or more there is one residual for every dataPoint added
+    // if ( this.dataPointsOnGraph.length > 3 ) {
+    //   this.addBestFitLineResidual( dataPoint );
+    // }
 
     dataPoint.positionUpdateListener = () => {
       this.update();
@@ -314,15 +311,15 @@
     const index = this.dataPointsOnGraph.indexOf( dataPoint );
     this.dataPointsOnGraph.splice( index, 1 );
 
-    this.removeMyLineResidual( dataPoint );
-
-    // if there are two dataPoints on the graph, remove all residuals
-    if ( this.dataPointsOnGraph.length === 2 ) {
-      this.removeBestFitLineResiduals();
-    }
-    else {
-      this.removeBestFitLineResidual( dataPoint );
-    }
+    // this.removeMyLineResidual( dataPoint );
+    //
+    // // if there are two dataPoints on the graph, remove all residuals
+    // if ( this.dataPointsOnGraph.length === 2 ) {
+    //   this.removeBestFitLineResiduals();
+    // }
+    // else {
+    //   this.removeBestFitLineResidual( dataPoint );
+    // }
 
     this.update();
     if ( dataPoint.positionUpdateListener && dataPoint.positionProperty.hasListener( dataPoint.positionUpdateListener ) ) {
@@ -334,7 +331,7 @@
    * Function that removes all the best Fit Line Residuals.
    */
   private removeBestFitLineResiduals(): void {
-    this.bestFitLineResiduals.clear();
+    // this.bestFitLineResiduals.clear();
   }
 
   /**
Index: js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts b/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts
--- a/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts	(date 1734714114915)
@@ -180,6 +180,7 @@
       const dataSetBounds = new Bounds2( selectedDataSet.xRange.min, selectedDataSet.yRange.min, selectedDataSet.xRange.max, selectedDataSet.yRange.max );
       // GraphAxesNode require a special modelView Transform that is set by the dataSet
       const modelViewTransformAxes = ModelViewTransform2.createRectangleInvertedYMapping( dataSetBounds, viewGraphBounds );
+
       graphAxesNode = new GraphAxesNode( selectedDataSet, modelViewTransformAxes, model.showGridProperty );
       this.addChild( graphAxesNode );
       graphAxesNode.moveToBack(); //

**Comment by KatieWoe** [comment]
This happens even if residuals are only selected after switching back to custom.

**Comment by samreid** [comment]
This patch looks like the right direction:

<details>

```diff

Subject: [PATCH] Rename vars, see https://github.com/phetsims/least-squares-regression/issues/96
---
Index: js/least-squares-regression/view/ResidualCanvasNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/view/ResidualCanvasNode.ts b/js/least-squares-regression/view/ResidualCanvasNode.ts
new file mode 100644
--- /dev/null	(date 1734717179929)
+++ b/js/least-squares-regression/view/ResidualCanvasNode.ts	(date 1734717179929)
@@ -0,0 +1,134 @@
+// Copyright 2015-2024, University of Colorado Boulder
+
+/**
+ * Render residual lines and squares.
+ *
+ * @author Sam Reid (PhET Interactive Simulations)
+ */
+
+import Bounds2 from '../../../../dot/js/Bounds2.js';
+import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
+import { CanvasNode } from '../../../../scenery/js/imports.js';
+import leastSquaresRegression from '../../leastSquaresRegression.js';
+import LeastSquaresRegressionConstants from '../LeastSquaresRegressionConstants.js';
+import Graph from '../model/Graph.js';
+import Residual from '../model/Residual.js';
+
+export default class ResidualCanvasNode extends CanvasNode {
+
+  public constructor(
+    public readonly graph: Graph,
+    public readonly modelViewTransform: ModelViewTransform2,
+    stageWidth: number, stageHeight: number ) {
+
+    super( {
+      canvasBounds: new Bounds2( 0, 0, stageWidth, stageHeight )
+    } );
+    this.invalidatePaint();
+    this.modelViewTransform = modelViewTransform;
+  }
+
+  public paintCanvas( context: CanvasRenderingContext2D ): void {
+
+    // --- SET CLIPPING REGION ---
+    context.save(); // Save context state before clipping
+
+    // Transform the graph's xRange and yRange to view coordinates
+    const xMinView = this.modelViewTransform.modelToViewX( this.graph.bounds.minX );
+    const xMaxView = this.modelViewTransform.modelToViewX( this.graph.bounds.maxX );
+    const yMinView = this.modelViewTransform.modelToViewY( this.graph.bounds.minY );
+    const yMaxView = this.modelViewTransform.modelToViewY( this.graph.bounds.maxY );
+
+    // Determine the clipping rectangle dimensions in view coordinates
+    const clipLeft = Math.min( xMinView, xMaxView );
+    const clipRight = Math.max( xMinView, xMaxView );
+    const clipTop = Math.min( yMinView, yMaxView );
+    const clipBottom = Math.max( yMinView, yMaxView );
+
+    const clipWidth = clipRight - clipLeft;
+    const clipHeight = clipBottom - clipTop;
+
+    // Define and activate the clipping region
+    context.beginPath();
+    context.rect( clipLeft, clipTop, clipWidth, clipHeight );
+    context.clip(); // Activate the clip region
+    context.closePath();
+    // --- CLIPPING END ---
+
+    // --- DRAW BACKGROUND FOR DEBUGGING ---
+    // Apply background color in view coordinates
+    // context.fillStyle = 'rgba(0,0,255,0.5)';
+    // context.fillRect( 0, 0, context.canvas.width, context.canvas.height );
+    // --- DRAW BACKGROUND END ---
+
+    // --- DEFINE HELPER FUNCTION TO DRAW RESIDUALS ---
+    const drawResidual = (
+      residual: Residual,
+      residualColor: string,
+      squaredResidualColor: string,
+      lineWidth: number
+    ) => {
+      // Convert residual points to view coordinates
+      const point1 = this.modelViewTransform.modelToViewPosition( residual.point1 );
+      const point2 = this.modelViewTransform.modelToViewPosition( residual.point2 );
+
+      // Draw residual line
+      context.beginPath();
+      context.moveTo( point1.x, point1.y );
+      context.strokeStyle = residualColor;
+      context.lineWidth = lineWidth;
+      context.lineTo( point2.x, point2.y );
+      context.stroke();
+      context.closePath();
+
+      // Calculate square residual dimensions
+      const top = Math.min( point1.y, point2.y );
+      const height = Math.abs( point1.y - point2.y );
+      const width = height; // Ensuring the square has equal width and height
+
+      // Determine the left position of the square based on residual direction
+      const left = residual.isSquaredResidualToTheLeft ? point1.x - width : point1.x;
+
+      // Draw square residual
+      context.beginPath();
+      context.fillStyle = squaredResidualColor;
+      context.rect( left, top, width, height );
+      context.fill(); // Fill square
+      context.closePath();
+    };
+    // --- HELPER FUNCTION END ---
+
+    // --- DRAW RESIDUALS ---
+    // Iterate over each data point on the graph
+    this.graph.dataPointsOnGraph.forEach( dataPoint => {
+      if ( this.graph.isLinearFitDefined() ) {
+        const linearFit = this.graph.getLinearFit();
+        const residual = new Residual( dataPoint, linearFit.slope, linearFit.intercept );
+
+        // Use helper function to draw residual for linear fit
+        drawResidual(
+          residual,
+          LeastSquaresRegressionConstants.BEST_FIT_LINE_COLOR.RESIDUAL_COLOR,
+          LeastSquaresRegressionConstants.BEST_FIT_LINE_COLOR.SQUARED_RESIDUAL_COLOR,
+          LeastSquaresRegressionConstants.RESIDUAL_LINE_WIDTH
+        );
+      }
+
+      // Create residual for "my line"
+      const myLineResidual = new Residual( dataPoint, this.graph.slope( this.graph.angleProperty.value ), this.graph.interceptProperty.value );
+
+      // Use helper function to draw residual for "my line"
+      drawResidual(
+        myLineResidual,
+        LeastSquaresRegressionConstants.MY_LINE_COLOR.RESIDUAL_COLOR,
+        LeastSquaresRegressionConstants.MY_LINE_COLOR.SQUARED_RESIDUAL_COLOR,
+        LeastSquaresRegressionConstants.RESIDUAL_LINE_WIDTH
+      );
+    } );
+    // --- RESIDUALS DRAWN ---
+
+    context.restore(); // Restore the context to remove the clipping region
+  }
+}
+
+leastSquaresRegression.register( 'ResidualCanvasNode', ResidualCanvasNode );
\ No newline at end of file
Index: js/least-squares-regression/view/GraphAxesNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/view/GraphAxesNode.ts b/js/least-squares-regression/view/GraphAxesNode.ts
--- a/js/least-squares-regression/view/GraphAxesNode.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/view/GraphAxesNode.ts	(date 1734714020819)
@@ -72,19 +72,28 @@
 
     showGridProperty.link( showGridPropertyObserver );
 
+    const xAxisNode = new XAxisNode( dataSet, modelViewTransform );
+    const yAxisNode = new YAxisNode( dataSet, modelViewTransform );
+    const xLabelNode = new XLabelNode( dataSet, modelViewTransform );
+    const yLabelNode = new YLabelNode( dataSet, modelViewTransform );
     super( {
       children: [
         new BackgroundNode( dataSet, modelViewTransform ),
         gridNode,
-        new XAxisNode( dataSet, modelViewTransform ),
-        new YAxisNode( dataSet, modelViewTransform ),
-        new XLabelNode( dataSet, modelViewTransform ),
-        new YLabelNode( dataSet, modelViewTransform )
+        xAxisNode,
+        yAxisNode,
+        xLabelNode,
+        yLabelNode
       ]
     } );
 
     this.disposeEmitter.addListener( () => {
       showGridProperty.unlink( showGridPropertyObserver );
+      xAxisNode.dispose();
+      yAxisNode.dispose();
+      xLabelNode.dispose();
+      yLabelNode.dispose();
+      gridNode.dispose();
     } );
   }
 }
@@ -302,6 +311,10 @@
       maxWidth: MAX_LABEL_WIDTH
     } );
     this.addChild( xLabelNode );
+
+    this.disposeEmitter.addListener( () => {
+      xLabelNode.dispose();
+    } );
   }
 }
 
@@ -327,6 +340,9 @@
     } );
     this.addChild( yLabelNode );
 
+    this.disposeEmitter.addListener( () => {
+      yLabelNode.dispose();
+    } );
   }
 }
 
Index: js/least-squares-regression/view/GraphNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/view/GraphNode.ts b/js/least-squares-regression/view/GraphNode.ts
--- a/js/least-squares-regression/view/GraphNode.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/view/GraphNode.ts	(date 1734715126290)
@@ -10,14 +10,12 @@
 import Multilink from '../../../../axon/js/Multilink.js';
 import Bounds2 from '../../../../dot/js/Bounds2.js';
 import { Shape } from '../../../../kite/js/imports.js';
-import affirm from '../../../../perennial-alias/js/browser-and-node/affirm.js';
-import arrayRemove from '../../../../phet-core/js/arrayRemove.js';
 import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
 import { Line, Node } from '../../../../scenery/js/imports.js';
 import leastSquaresRegression from '../../leastSquaresRegression.js';
 import LeastSquaresRegressionConstants from '../LeastSquaresRegressionConstants.js';
 import Graph from '../model/Graph.js';
-import ResidualLineAndSquareNode from './ResidualLineAndSquareNode.js';
+import ResidualCanvasNode from './ResidualCanvasNode.js';
 
 export default class GraphNode extends Node {
   private readonly myLine: Line;
@@ -25,7 +23,8 @@
 
   // we need to track the best fit residuals in a separate array so that we can toggle their visibility when
   // the best fit is undefined
-  private readonly bestFitResiduals: Node[] = [];
+  // private readonly bestFitResiduals: Node[] = [];
+  private readonly residualCanvasNode: ResidualCanvasNode;
 
   public constructor( public readonly graph: Graph,
                       public readonly viewBounds: Bounds2,
@@ -77,61 +76,63 @@
     Multilink.multilink( [ graph.angleProperty, graph.interceptProperty ], ( angle, intercept ) => {
       const slope = graph.slope( angle );
       updateMyLine( slope, intercept );
-      graph.updateMyLineResiduals();
+      // graph.updateMyLineResiduals();
     } );
 
     // we will add all the residuals in a separate node
     const residualsLayer = new Node();
+    this.residualCanvasNode = new ResidualCanvasNode( graph, modelViewTransform, 1000, 1000 );
+    residualsLayer.addChild( this.residualCanvasNode );
 
     // Handle the comings and goings of 'My Line' Residuals. Recall that graph.myLineResiduals is an
     // observable array of Property.<Residual>
-    graph.myLineResiduals.addItemAddedListener( addedResidualProperty => {
-
-      // Create and add the view representation for this residual.
-      const residualNode = new ResidualLineAndSquareNode(
-        addedResidualProperty,
-        LeastSquaresRegressionConstants.MY_LINE_COLOR,
-        this.viewBounds,
-        modelViewTransform,
-        graph.myLineResidualsVisibleProperty,
-        graph.myLineSquaredResidualsVisibleProperty );
-      residualsLayer.addChild( residualNode );
-    } );
-    graph.myLineResiduals.addItemRemovedListener( removedResidualProperty => {
-
-      // find the matching ResidualLineAndSquareNode
-      const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
-      assert && assert( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
-      residualsLayer.removeChild( residualNode[ 0 ] );
-      residualNode[ 0 ].dispose();
-    } );
-
-    // Handle the comings and goings of Best Fit Line Residuals. Recall that graph.bestFitResiduals is an
-    // observable array of Property.<Residual>
-    graph.bestFitLineResiduals.addItemAddedListener( addedResidualProperty => {
-
-      // Create and add the view representation for this residual.
-      const residualNode = new ResidualLineAndSquareNode(
-        addedResidualProperty,
-        LeastSquaresRegressionConstants.BEST_FIT_LINE_COLOR,
-        this.viewBounds,
-        modelViewTransform,
-        graph.bestFitLineResidualsVisibleProperty,
-        graph.bestFitLineSquaredResidualsVisibleProperty );
-      residualsLayer.addChild( residualNode );
-
-      this.bestFitResiduals.push( residualNode );
-    } );
-    // Add the removal listener for if and when this residual is removed from the model.
-    graph.bestFitLineResiduals.addItemRemovedListener( removedResidualProperty => {
-
-      // Find the matching ResidualLineAndSquareNode
-      const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
-      affirm( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
-      arrayRemove( this.bestFitResiduals, residualNode[ 0 ] );
-      residualsLayer.removeChild( residualNode[ 0 ] );
-      residualNode[ 0 ].dispose();
-    } );
+    // graph.myLineResiduals.addItemAddedListener( addedResidualProperty => {
+    //
+    //   // Create and add the view representation for this residual.
+    //   const residualNode = new ResidualLineAndSquareNode(
+    //     addedResidualProperty,
+    //     LeastSquaresRegressionConstants.MY_LINE_COLOR,
+    //     this.viewBounds,
+    //     modelViewTransform,
+    //     graph.myLineResidualsVisibleProperty,
+    //     graph.myLineSquaredResidualsVisibleProperty );
+    //   residualsLayer.addChild( residualNode );
+    // } );
+    // graph.myLineResiduals.addItemRemovedListener( removedResidualProperty => {
+    //
+    //   // find the matching ResidualLineAndSquareNode
+    //   const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
+    //   assert && assert( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
+    //   residualsLayer.removeChild( residualNode[ 0 ] );
+    //   residualNode[ 0 ].dispose();
+    // } );
+    //
+    // // Handle the comings and goings of Best Fit Line Residuals. Recall that graph.bestFitResiduals is an
+    // // observable array of Property.<Residual>
+    // graph.bestFitLineResiduals.addItemAddedListener( addedResidualProperty => {
+    //
+    //   // Create and add the view representation for this residual.
+    //   const residualNode = new ResidualLineAndSquareNode(
+    //     addedResidualProperty,
+    //     LeastSquaresRegressionConstants.BEST_FIT_LINE_COLOR,
+    //     this.viewBounds,
+    //     modelViewTransform,
+    //     graph.bestFitLineResidualsVisibleProperty,
+    //     graph.bestFitLineSquaredResidualsVisibleProperty );
+    //   residualsLayer.addChild( residualNode );
+    //
+    //   this.bestFitResiduals.push( residualNode );
+    // } );
+    // // Add the removal listener for if and when this residual is removed from the model.
+    // graph.bestFitLineResiduals.addItemRemovedListener( removedResidualProperty => {
+    //
+    //   // Find the matching ResidualLineAndSquareNode
+    //   const residualNode = residualsLayer.children.filter( node => node instanceof ResidualLineAndSquareNode && node.residualProperty === removedResidualProperty );
+    //   affirm( residualNode.length === 1, 'ResidualLineAndSquareNode not found' );
+    //   arrayRemove( this.bestFitResiduals, residualNode[ 0 ] );
+    //   residualsLayer.removeChild( residualNode[ 0 ] );
+    //   residualNode[ 0 ].dispose();
+    // } );
 
     // Hide or show the visibility of 'MyLine' and 'BestFitLine', both listeners are present for the lifetime of the sim
     graph.myLineVisibleProperty.linkAttribute( this.myLine, 'visible' );
@@ -145,6 +146,10 @@
     this.addChild( this.bestFitLine );
   }
 
+  public step( dt: number ): void {
+    this.residualCanvasNode.invalidatePaint();
+  }
+
   /**
    * Resets values to their original state
    */
@@ -154,9 +159,6 @@
 
   public update(): void {
     this.updateBestFitLine();
-
-    // make sure that the best fit residuals are only visible when the best fit line is defined
-    this.updateBestFitResidualsVisible();
   }
 
   /**
@@ -175,16 +177,6 @@
       this.bestFitLine.setPoint2( 0, 0 ); // of length zero
     }
   }
-
-  /**
-   * Make sure that the best fit residuals and squares are only visible if the linear fit is defined.
-   * This visibility is separate from the visibility handled by the control panel
-   */
-  public updateBestFitResidualsVisible(): void {
-    for ( let i = 0; i < this.bestFitResiduals.length; i++ ) {
-      this.bestFitResiduals[ i ].visible = this.graph.isLinearFitDefined();
-    }
-  }
 }
 
 leastSquaresRegression.register( 'GraphNode', GraphNode );
\ No newline at end of file
Index: js/least-squares-regression/model/Graph.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/model/Graph.ts b/js/least-squares-regression/model/Graph.ts
--- a/js/least-squares-regression/model/Graph.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/model/Graph.ts	(date 1734717501055)
@@ -10,17 +10,14 @@
  */
 
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
-import createObservableArray, { ObservableArray } from '../../../../axon/js/createObservableArray.js';
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
 import NumberProperty from '../../../../axon/js/NumberProperty.js';
-import Property from '../../../../axon/js/Property.js';
 import TReadOnlyProperty from '../../../../axon/js/TReadOnlyProperty.js';
 import Bounds2 from '../../../../dot/js/Bounds2.js';
 import Range from '../../../../dot/js/Range.js';
 import Vector2 from '../../../../dot/js/Vector2.js';
 import leastSquaresRegression from '../../leastSquaresRegression.js';
 import DataPoint from './DataPoint.js';
-import Residual from './Residual.js';
 
 /**
  * Graph model for handling data points, residuals, and statistics related to lines of best fit.
@@ -46,11 +43,6 @@
   // Bounds for the graph in model coordinates, it is a unit square. This remains the same for all DataSets
   public readonly bounds: Bounds2;
 
-  // Observable arrays for residuals
-  // Each entry is a Property<Residual>.
-  public readonly myLineResiduals: ObservableArray<Property<Residual>>;
-  public readonly bestFitLineResiduals: ObservableArray<Property<Residual>>;
-
   // Array of dataPoints currently on the graph
   public dataPointsOnGraph: DataPoint[];
 
@@ -103,10 +95,6 @@
 
     this.bounds = new Bounds2( 0, 0, 1, 1 );
 
-    // observable arrays of the line and squared residuals (wrapped in a property) for MyLine and BestFitLine
-    this.myLineResiduals = createObservableArray<Property<Residual>>();
-    this.bestFitLineResiduals = createObservableArray<Property<Residual>>();
-
     // array of the dataPoints that are overlapping the graph.
     this.dataPointsOnGraph = [];
 
@@ -128,8 +116,6 @@
     this.bestFitLineShowResidualsProperty.reset();
     this.bestFitLineShowSquaredResidualsProperty.reset();
     this.dataPointsOnGraph = [];
-    this.myLineResiduals.clear();
-    this.bestFitLineResiduals.clear();
   }
 
   /**
@@ -137,8 +123,6 @@
    */
   public resetOnChangeOfDataSet(): void {
     this.dataPointsOnGraph = [];
-    this.myLineResiduals.clear();
-    this.bestFitLineResiduals.clear();
   }
 
   /**
@@ -154,116 +138,12 @@
   }
 
   /**
-   * Update the model Residuals for 'My Line' and 'Best Fit Line'.
-   */
-  private update(): void {
-    this.updateMyLineResiduals();
-    this.updateBestFitLineResiduals();
-  }
-
-  /**
-   * Convert the angle of a line (measured from the horizontal x axis) to a slope.
+   * Convert the angle of a line (measured from the horizontal x-axis) to a slope.
    */
   public slope( angle: number ): number {
     return Math.tan( angle ) * this.bounds.height / this.bounds.width;
   }
 
-  /**
-   * Add a 'My Line' model Residual to a dataPoint.
-   */
-  private addMyLineResidual( dataPoint: DataPoint ): void {
-    const myLineResidual = new Residual( dataPoint, this.slope( this.angleProperty.value ), this.interceptProperty.value );
-    this.myLineResiduals.push( new Property( myLineResidual ) );
-  }
-
-  /**
-   * Add a 'Best Fit Line' model Residual to a dataPoint.
-   */
-  private addBestFitLineResidual( dataPoint: DataPoint ): void {
-    const linearFitParameters = this.getLinearFit();
-    const bestFitLineResidual = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
-    this.bestFitLineResiduals.push( new Property( bestFitLineResidual ) );
-  }
-
-  /**
-   * Remove the 'My Line' model Residual attached to a dataPoint.
-   */
-  private removeMyLineResidual( dataPoint: DataPoint ): void {
-    const myLineResidualsCopy = this.myLineResiduals.slice();
-    myLineResidualsCopy.forEach( myLineResidualProperty => {
-      if ( myLineResidualProperty.value.dataPoint === dataPoint ) {
-        this.myLineResiduals.remove( myLineResidualProperty );
-      }
-    } );
-  }
-
-  /**
-   * Remove a 'Best Fit Line' model Residual attached to a dataPoint.
-   */
-  private removeBestFitLineResidual( dataPoint: DataPoint ): void {
-    const bestFitLineResidualsCopy = this.bestFitLineResiduals.slice();
-    bestFitLineResidualsCopy.forEach( bestFitLineResidualProperty => {
-      if ( bestFitLineResidualProperty.value.dataPoint === dataPoint ) {
-        this.bestFitLineResiduals.remove( bestFitLineResidualProperty );
-      }
-    } );
-  }
-
-  /**
-   * Update all 'My Line' model Residuals
-   * (Necessary to update when the slope and the intercept of 'My Line' are modified)
-   */
-  public updateMyLineResiduals(): void {
-    this.myLineResiduals.forEach( residualProperty => {
-      const dataPoint = residualProperty.value.dataPoint;
-      residualProperty.value = new Residual( dataPoint, this.slope( this.angleProperty.value ), this.interceptProperty.value );
-    } );
-  }
-
-  /**
-   * Update all 'Best Fit Line' model Residuals.
-   */
-  private updateBestFitLineResiduals(): void {
-    if ( this.isLinearFitDefined() ) {
-      const linearFitParameters = this.getLinearFit();
-      this.bestFitLineResiduals.forEach( residualProperty => {
-        const dataPoint = residualProperty.value.dataPoint;
-        residualProperty.value = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
-      } );
-    }
-  }
-
-  /**
-   * Add Data Points on Graph in bulk, for performance reasons.
-   */
-  public addDataPointsOnGraphAndResidualsInBulk( dataPoints: DataPoint[] ): void {
-    // for performance reason one should add all the dataPoints on the graph
-    // then we can calculate the best Fit Line (only once)
-    // and then add all the Residuals.
-    dataPoints.forEach( dataPoint => {
-      this.dataPointsOnGraph.push( dataPoint );
-    } );
-
-    const mySlope = this.slope( this.angleProperty.value );
-    const myIntercept = this.interceptProperty.value;
-
-    // add a 'myLineResidual' for every single dataPoint
-    dataPoints.forEach( dataPoint => {
-      const myLineResidual = new Residual( dataPoint, mySlope, myIntercept );
-      this.myLineResiduals.push( new Property( myLineResidual ) );
-    } );
-
-    // add a 'best fit Line' residual  for every single dataPoint
-    // unless there is not  linearFit (because there is less than 2 data points on the board for instance)
-    if ( this.isLinearFitDefined() ) {
-      const linearFitParameters = this.getLinearFit();
-      dataPoints.forEach( dataPoint => {
-        const bestFitLineResidual = new Residual( dataPoint, linearFitParameters.slope, linearFitParameters.intercept );
-        this.bestFitLineResiduals.push( new Property( bestFitLineResidual ) );
-      } );
-    }
-  }
-
   /**
    * Function that returns true if the dataPoint is on the array.
    */
@@ -284,26 +164,6 @@
    */
   public addPointAndResiduals( dataPoint: DataPoint ): void {
     this.dataPointsOnGraph.push( dataPoint );
-    this.addMyLineResidual( dataPoint );
-
-    // a BestFit line exists if there are two dataPoints or more.
-    // if there are two dataPoints on the graph, we don't add my bestFitLine residual
-    // since the residual are zero by definition
-    // if there are exactly three data points on the graph we need to add three residuals
-    if ( this.dataPointsOnGraph.length === 3 ) {
-      this.dataPointsOnGraph.forEach( dataPoint => {
-        this.addBestFitLineResidual( dataPoint );
-      } );
-    }
-    // for three dataPoints or more there is one residual for every dataPoint added
-    if ( this.dataPointsOnGraph.length > 3 ) {
-      this.addBestFitLineResidual( dataPoint );
-    }
-
-    dataPoint.positionUpdateListener = () => {
-      this.update();
-    };
-    dataPoint.positionProperty.link( dataPoint.positionUpdateListener );
   }
 
   /**
@@ -313,30 +173,11 @@
     assert && assert( this.isDataPointOnList( dataPoint ), ' need the point to be on the list to remove it' );
     const index = this.dataPointsOnGraph.indexOf( dataPoint );
     this.dataPointsOnGraph.splice( index, 1 );
-
-    this.removeMyLineResidual( dataPoint );
-
-    // if there are two dataPoints on the graph, remove all residuals
-    if ( this.dataPointsOnGraph.length === 2 ) {
-      this.removeBestFitLineResiduals();
-    }
-    else {
-      this.removeBestFitLineResidual( dataPoint );
-    }
-
-    this.update();
     if ( dataPoint.positionUpdateListener && dataPoint.positionProperty.hasListener( dataPoint.positionUpdateListener ) ) {
       dataPoint.positionProperty.unlink( dataPoint.positionUpdateListener );
     }
   }
 
-  /**
-   * Function that removes all the best Fit Line Residuals.
-   */
-  private removeBestFitLineResiduals(): void {
-    this.bestFitLineResiduals.clear();
-  }
-
   /**
    * Function that returns the sum of squared residuals of all the dataPoints on the list (compared with a line with a slope and intercept)
    */
@@ -486,12 +327,12 @@
 
       // make sure the denominator is not equal to zero, this happens if all the points are aligned vertically
     if ( pearsonCoefficientCorrelationDenominator === 0 ) {
-        return null; //
+      return null;
     }
-      else {
-    const pearsonCoefficientCorrelation = pearsonCoefficientCorrelationNumerator / pearsonCoefficientCorrelationDenominator;
-    return pearsonCoefficientCorrelation;
-      }
+    else {
+      const pearsonCoefficientCorrelation = pearsonCoefficientCorrelationNumerator / pearsonCoefficientCorrelationDenominator;
+      return pearsonCoefficientCorrelation;
+    }
     }
   }
 }
Index: js/least-squares-regression/model/LeastSquaresRegressionModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/model/LeastSquaresRegressionModel.ts b/js/least-squares-regression/model/LeastSquaresRegressionModel.ts
--- a/js/least-squares-regression/model/LeastSquaresRegressionModel.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/model/LeastSquaresRegressionModel.ts	(date 1734717458880)
@@ -117,9 +117,7 @@
         savedCustomDataPoints.forEach( dataPoint => {
           this.dataPoints.push( new DataPoint( dataPoint.copy() ) );
         } );
-        // Add the Data Points on Graph and all the Residuals
-        // For performance reason, we do it in bulk so that we don't constantly update the residuals after adding a dataPoint
-        this.graph.addDataPointsOnGraphAndResidualsInBulk( this.dataPoints );
+
         this.dataPoints.forEach( dataPoint => {
           this.addDataPointControlledListener( dataPoint );
         } );
@@ -147,10 +145,12 @@
           const positionVector = new Vector2( xNormalized, yNormalized );
           this.dataPoints.push( new DataPoint( positionVector ) );
         } );
-        // Add the Data Points on Graph and all the Residuals
-        // For performance reason, we do it in bulk so that we don't constantly update the residuals after adding a dataPoint
-        this.graph.addDataPointsOnGraphAndResidualsInBulk( this.dataPoints );
-      }
+      }
+
+      // Add the Data Points on Graph and all the Residuals
+      // For performance reason, we do it in bulk so that we don't constantly update the residuals after adding a dataPoint
+      this.dataPoints.forEach( dataPoint => this.graph.dataPointsOnGraph.push( dataPoint ) );
+
       // Since we added the dataPoints in Bulk, let's send a trigger to the view
       this.dataPointsAddedEmitter.emit();
     } );
Index: js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts b/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts
--- a/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts	(revision 534ea86a0186060ea7bb11dec5ac021a9e65b0ca)
+++ b/js/least-squares-regression/view/LeastSquaresRegressionScreenView.ts	(date 1734714666821)
@@ -67,6 +67,7 @@
 ];
 
 export default class LeastSquaresRegressionScreenView extends ScreenView {
+  private readonly graphNode: GraphNode;
 
   public constructor( model: LeastSquaresRegressionModel ) {
 
@@ -97,14 +98,14 @@
     const myLineControlPanel = new MyLineControlPanel( model.graph, model.dataPointsAddedEmitter, panelOptions );
 
     // Create the Graph Node which is responsible for 'My Line', 'Best Fit Line' and the Residuals representation
-    const graphNode = new GraphNode( model.graph, viewGraphBounds, modelViewTransform );
+    this.graphNode = new GraphNode( model.graph, viewGraphBounds, modelViewTransform );
 
     // Create the Graph Axes, including the tick marks, labels and axis titles
     let graphAxesNode = new GraphAxesNode( model.selectedDataSetProperty.value, modelViewTransform, model.showGridProperty );
 
     // Create the dataSet combo box that appears on top of the graph
     // Width of contents limited by width of graphNode for i18n
-    const dataSetLabelMaxWidth = graphNode.width / 2;
+    const dataSetLabelMaxWidth = this.graphNode.width / 2;
     const dataSetListParent = new Node();
     const dataSetComboBox = new DataSetComboBox( model.selectedDataSetProperty, model.dataSets, dataSetListParent, dataSetLabelMaxWidth );
 
@@ -180,12 +181,13 @@
       const dataSetBounds = new Bounds2( selectedDataSet.xRange.min, selectedDataSet.yRange.min, selectedDataSet.xRange.max, selectedDataSet.yRange.max );
       // GraphAxesNode require a special modelView Transform that is set by the dataSet
       const modelViewTransformAxes = ModelViewTransform2.createRectangleInvertedYMapping( dataSetBounds, viewGraphBounds );
+
       graphAxesNode = new GraphAxesNode( selectedDataSet, modelViewTransformAxes, model.showGridProperty );
       this.addChild( graphAxesNode );
       graphAxesNode.moveToBack(); //
 
       // Update the graphNode (will populate it with the new dataPoints)
-      graphNode.update();
+      this.graphNode.update();
 
       // Update the Pearson Correlation Coefficient Panel
       correlationCoefficientAccordionBox.update();
@@ -238,7 +240,7 @@
           bestFitLineAccordionBox.updateBestFitLineEquation();
           bestFitLineAccordionBox.sumOfSquaredResidualsChart.updateWidth();
           myLineControlPanel.sumOfSquaredResiduals.updateWidth();
-          graphNode.update();
+          this.graphNode.update();
           correlationCoefficientAccordionBox.update();
         };
 
@@ -296,7 +298,7 @@
     const resetAllButton = new ResetAllButton( {
       listener: () => {
         model.reset();
-        graphNode.reset();
+        this.graphNode.reset();
         correlationCoefficientAccordionBox.reset();
         bestFitLineAccordionBox.reset();
         myLineControlPanel.reset();
@@ -315,7 +317,7 @@
     this.addChild( dataSetComboBox );
     this.addChild( infoButton );
     this.addChild( backLayer );
-    this.addChild( graphNode );
+    this.addChild( this.graphNode );
 
     // Order matters here. These must come last
     this.addChild( bucketFrontLayer ); //must come after back layer
@@ -339,6 +341,11 @@
     }
   }
 
+  public override step( dt: number ): void {
+    super.step( dt );
+    this.graphNode.step( dt );
+  }
+
   /**
    * This is taken from MoleculesAndLightScreenView with modifications.
    *

**Comment by samreid** [comment]
@Nancy-Salpepi can you please verify that this is fixed in main? I have rewritten the residual line and square rendering, please double check that I didn't disrupt correct behavior.

**Comment by Nancy-Salpepi** [comment]
I see an issue related to the eraser button. Not all the data points return to the bucket and for the data points that do return, their residuals are still present. 

Steps:
1. Check all boxes in Best-Fit Line accordion panel: Best-Fit Line, Residuals, and Square Residuals
2. Add 3 data points to the play area
3. Select Height vs. Shoe Size from the combo box
4. Select Custom
5. Press Eraser button

<img width="558" alt="Screenshot 2024-12-20 at 4 06 27 PM" src="https://github.com/user-attachments/assets/9aa3e0f1-86aa-4661-a734-dfdd945a6aef" />

**Comment by samreid** [comment]
Thanks @Nancy-Salpepi, good catch. It is hopefully resolved in the commit, can you please test?

**Comment by Nancy-Salpepi** [comment]
Things look good now! 
Closing.
